
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xixicikohbspyfdkatwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpeGljaWtvaGJzcHlmZGthdHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Nzk4MzIsImV4cCI6MjA1OTM1NTgzMn0.V-zeBIWT9EfGAqAcn_yo3hHVD74CsZnENDVWYa9936Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type-safe helper functions for accessing tables
export const from = {
  profiles: () => supabase.from('profiles'),
  userConnections: () => supabase.from('User_Connections'),
};
